name: Bug report
description: Report a bug or unexpected behaviour
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the bug?
    validations:
      required: true

  - type: input
    id: module
    attributes:
      label: Module / SKU
      placeholder: CH-HMI-SENS-...

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How can the issue be reproduced?

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Hardware revision, firmware version, OS, etc.
